// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['backend']['App']['AddConnection'](arg1);
}

export function BrowseFTPDirectory(arg1, arg2) {
  return window['go']['backend']['App']['BrowseFTPDirectory'](arg1, arg2);
}

export function BrowseSFTPDirectory(arg1, arg2) {
  return window['go']['backend']['App']['BrowseSFTPDirectory'](arg1, arg2);
}

export function BrowseSMBDirectory(arg1, arg2, arg3) {
  return window['go']['backend']['App']['BrowseSMBDirectory'](arg1, arg2, arg3);
}

export function ClearSystemLogs() {
  return window['go']['backend']['App']['ClearSystemLogs']();
}

export function ConnectBatch(arg1) {
  return window['go']['backend']['App']['ConnectBatch'](arg1);
}

export function ConnectSingle(arg1) {
  return window['go']['backend']['App']['ConnectSingle'](arg1);
}

export function DeleteBatchConnections(arg1) {
  return window['go']['backend']['App']['DeleteBatchConnections'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['backend']['App']['DeleteConnection'](arg1);
}

export function DeleteVulnerability(arg1) {
  return window['go']['backend']['App']['DeleteVulnerability'](arg1);
}

export function DownloadFTPFile(arg1, arg2) {
  return window['go']['backend']['App']['DownloadFTPFile'](arg1, arg2);
}

export function DownloadSFTPFile(arg1, arg2) {
  return window['go']['backend']['App']['DownloadSFTPFile'](arg1, arg2);
}

export function DownloadSMBFile(arg1, arg2, arg3) {
  return window['go']['backend']['App']['DownloadSMBFile'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['backend']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteContainerCommand(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExecuteContainerCommand'](arg1, arg2, arg3);
}

export function ExportReport(arg1) {
  return window['go']['backend']['App']['ExportReport'](arg1);
}

export function GetAllVulnerabilities() {
  return window['go']['backend']['App']['GetAllVulnerabilities']();
}

export function GetConnections(arg1) {
  return window['go']['backend']['App']['GetConnections'](arg1);
}

export function GetDockerContainers(arg1) {
  return window['go']['backend']['App']['GetDockerContainers'](arg1);
}

export function GetK8sPods(arg1) {
  return window['go']['backend']['App']['GetK8sPods'](arg1);
}

export function GetProxySettings() {
  return window['go']['backend']['App']['GetProxySettings']();
}

export function GetServiceTypes() {
  return window['go']['backend']['App']['GetServiceTypes']();
}

export function GetSystemLogs() {
  return window['go']['backend']['App']['GetSystemLogs']();
}

export function GetVulnerabilityByServiceType(arg1) {
  return window['go']['backend']['App']['GetVulnerabilityByServiceType'](arg1);
}

export function ImportCSV() {
  return window['go']['backend']['App']['ImportCSV']();
}

export function SaveVulnerability(arg1) {
  return window['go']['backend']['App']['SaveVulnerability'](arg1);
}

export function SelectDirectory() {
  return window['go']['backend']['App']['SelectDirectory']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['backend']['App']['UpdateConnection'](arg1, arg2);
}

export function UpdateProxySettings(arg1) {
  return window['go']['backend']['App']['UpdateProxySettings'](arg1);
}
