// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {context} from '../models';

export function AddConnection(arg1:models.ConnectionRequest):Promise<models.Connection>;

export function BrowseFTPDirectory(arg1:string,arg2:string):Promise<string>;

export function BrowseSFTPDirectory(arg1:string,arg2:string):Promise<string>;

export function BrowseSMBDirectory(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearSystemLogs():Promise<void>;

export function ConnectBatch(arg1:Array<string>):Promise<number>;

export function ConnectSingle(arg1:string):Promise<void>;

export function DeleteBatchConnections(arg1:Array<string>):Promise<number>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteVulnerability(arg1:string):Promise<void>;

export function DownloadFTPFile(arg1:string,arg2:string):Promise<void>;

export function DownloadSFTPFile(arg1:string,arg2:string):Promise<void>;

export function DownloadSMBFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExecuteContainerCommand(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportReport(arg1:services.ExportReportRequest):Promise<string>;

export function GetAllVulnerabilities():Promise<Array<models.VulnerabilityInfo>>;

export function GetConnections(arg1:string):Promise<Array<models.Connection>>;

export function GetDockerContainers(arg1:string):Promise<string>;

export function GetK8sPods(arg1:string):Promise<string>;

export function GetProxySettings():Promise<models.ProxyConfig>;

export function GetServiceTypes():Promise<Array<Record<string, any>>>;

export function GetSystemLogs():Promise<Array<string>>;

export function GetVulnerabilityByServiceType(arg1:string):Promise<models.VulnerabilityInfo>;

export function ImportCSV():Promise<number>;

export function SaveVulnerability(arg1:models.VulnerabilityInfo):Promise<void>;

export function SelectDirectory():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:models.ConnectionRequest):Promise<string>;

export function UpdateConnection(arg1:string,arg2:models.ConnectionRequest):Promise<void>;

export function UpdateProxySettings(arg1:models.ProxyConfig):Promise<void>;
