// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowUnmaximize() {
  return window['go']['main']['App']['WindowUnmaximize']();
}
