// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WindowClose():Promise<void>;

export function WindowIsMaximized():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowUnmaximize():Promise<void>;
